### ISSUE TITLE
Release 1.0.2 with https://github.com/panmitz/SPARQL-Burger/pull/4

### ISSUE THREAD

**Issue by davidandreoletti** [panmitz/SPARQL-Burger#6]
Hi, 

I am a user of your library and would like to use [Values](https://github.com/panmitz/SPARQL-Burger/pull/4) added in 2022. However, Pypi only has [v1.0.1 (released in 2020)](https://pypi.org/project/SPARQL-Burger/1.0.1/).

Would you consider releasing a new version ?

**Comment by panmitz** [comment]
Hi there @davidandreoletti . Sure, I’ll make a new release the soonest. Sorry, I’m pretty busy this week, it might take me few days

**Comment by davidandreoletti** [comment]
At your earliest convenience is fine for me :-)

Thank you for the library.

**Comment by panmitz** [comment]
@davidandreoletti version 1.0.2 now released, both in GitHub and PyPI. Cheers

**Comment by davidandreoletti** [comment]
Superb! Thank you.
